'use strict';
const $=s=>document.querySelector(s);
const PUBLIC=Boolean(document.querySelector('meta[name=public-collection]'));
let publicData=null,publicFetched=0;
async function publicApi(path,post){
 if(post)throw Error('Управлението е достъпно само за собственика.');
 if(!publicData||Date.now()-publicFetched>60000){const r=await fetch('./data.json',{cache:'no-cache'});if(!r.ok)throw Error('Колекцията временно не е достъпна.');publicData=await r.json();publicFetched=Date.now();}
 const u=new URL(path,location.href);
 if(u.pathname==='/api/status'){const counts={};for(const j of publicData.items)counts[j.category]=(counts[j.category]||0)+1;return {total:publicData.items.length,topics:Object.entries(counts).map(([category,count])=>({category,count})).sort((a,b)=>a.category.localeCompare(b.category,'bg')),updated_at:publicData.updated_at,checked_at:publicData.checked_at};}
 const q=(u.searchParams.get('q')||'').toLocaleLowerCase('bg');const cat=u.searchParams.get('category')||'';const page=Math.max(1,Number(u.searchParams.get('page'))||1);let rows=publicData.items.filter(j=>(!cat||j.category===cat)&&(!q||j.text.toLocaleLowerCase('bg').includes(q)));
 if(u.searchParams.get('random')==='1')return {items:rows.length?[rows[Math.floor(Math.random()*rows.length)]]:[],total:rows.length};
 return {items:rows.slice((page-1)*18,page*18),total:rows.length,page};
}
let category='',page=1,query='',state=null,serial=0,lastTotal=-1;
const date=s=>s?new Date(s).toLocaleString('bg-BG',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;}
async function api(path,post=false){if(PUBLIC)return publicApi(path,post);const r=await fetch(path,post?{method:'POST',headers:{'X-Jokes-Request':'1'}}:{});const d=await r.json();if(!r.ok)throw Error(d.error||'Връзката със сървъра е прекъсната.');return d;}
function link(label,url){const a=el('a',label);a.href=url;a.target='_blank';a.rel='noopener noreferrer';return a;}
function card(j){const a=el('article',undefined,'card');const top=el('div',undefined,'card-top');top.append(el('span',j.category,'tag'),el('span','“','quote'));a.append(top,el('p',j.text,'joke-text'));const bottom=el('div',undefined,'card-bottom');bottom.append(link('Източник ↗',j.source_url),link('Лиценз',j.license_url),el('span','Добавен '+date(j.published_at)));a.append(bottom);return a;}
async function load(){const request=++serial;$('#cards').setAttribute('aria-busy','true');try{const params=new URLSearchParams({q:query,category,page});const d=await api('/api/jokes?'+params);if(request!==serial)return;$('#cards').replaceChildren(...d.items.map(card));$('#results').textContent=`${d.total} вица${category?' · '+category:''}`;$('#empty').hidden=!!d.items.length;$('#empty-text').textContent=state?.total?'Опитай друга дума или тема.':'Колекцията се попълва от интернет. Виж състоянието на автоматичното търсене по-долу.';$('#page').textContent=`${page} / ${Math.max(1,Math.ceil(d.total/18))}`;$('#prev').disabled=page===1;$('#next').disabled=page*18>=d.total;$('#clear').hidden=!category&&!query;}catch(e){$('#results').textContent=e.message;}finally{if(request===serial)$('#cards').setAttribute('aria-busy','false');}}
function topics(){const all=[{category:'',count:state.total},...state.topics];$('#topics').replaceChildren(...all.map(t=>{const b=el('button',t.category||'Всички','topic');b.append(el('span',String(t.count)));b.setAttribute('aria-pressed',String(category===t.category));b.onclick=()=>{category=t.category;page=1;topics();load();};return b;}));}
async function refresh(){try{const s=await api('/api/status');state=s;$('#total').textContent=s.total;if(PUBLIC){$('#auto-status').textContent='Колекцията е онлайн';$('#next-check').textContent=(s.checked_at?'Последна проверка: ':'Последно обновяване: ')+date(s.checked_at||s.updated_at);if(lastTotal!==s.total){lastTotal=s.total;topics();await load();}return;}$('#auto-status').textContent=s.running?'Търсим нови усмивки…':s.enabled?'Автоматично попълване':'Автоматичното попълване е на пауза';$('#next-check').textContent=s.next_at?'Следваща проверка: '+date(s.next_at):'';$('#pause').textContent=s.enabled?'Пауза':'Продължи';$('#import').disabled=s.running;$('#withheld').textContent=`${s.withheld} текста са задържани от езиковата проверка и не са публикувани.`;$('#runs').replaceChildren(...s.runs.slice(0,4).map(r=>{const box=el('div',undefined,'run');box.append(el('div',`${date(r.started_at)} · ${r.finished_at?`${r.added} нови · ${r.duplicates} повторения · ${r.withheld} задържани`:'Търсене в интернет…'}`));for(const err of r.errors)box.append(el('p',err,'error'));return box;}));if(lastTotal!==s.total){lastTotal=s.total;topics();await load();}}catch(e){$('#auto-status').textContent='Няма връзка със сървъра';$('#next-check').textContent='Колекцията ще се обнови при възстановяване на връзката.';}}
let debounce;$('#search').oninput=()=>{clearTimeout(debounce);debounce=setTimeout(()=>{query=$('#search').value.trim();page=1;load();},200);};$('#clear').onclick=()=>{query='';category='';page=1;$('#search').value='';topics();load();};$('#prev').onclick=()=>{page--;load();$('#collection').scrollIntoView();};$('#next').onclick=()=>{page++;load();$('#collection').scrollIntoView();};
async function randomJoke(){try{const d=await api('/api/jokes?random=1');$('#random-content').replaceChildren(d.items.length?card(d.items[0]):el('p','Все още събираме първите вицове. Опитай след малко.'));if(!$('#joke-dialog').open)$('#joke-dialog').showModal();}catch(e){$('#action-message').textContent=e.message;}}
$('#random').onclick=randomJoke;$('#another').onclick=randomJoke;$('#close-dialog').onclick=()=>$('#joke-dialog').close();
if($('#import'))$('#import').onclick=async()=>{try{$('#import').disabled=true;await api('/api/import',true);$('#action-message').textContent='Търсенето започна. Старите вицове остават в колекцията.';await refresh();}catch(e){$('#action-message').textContent=e.message;$('#import').disabled=false;}};
if($('#pause'))$('#pause').onclick=async()=>{if(!state)return;try{await api(state.enabled?'/api/pause':'/api/resume',true);await refresh();}catch(e){$('#action-message').textContent=e.message;}};
refresh();setInterval(refresh,PUBLIC?60000:5000);
